version: '2'

services:
  app:
    container_name: test_app
    build:
      dockerfile: Dockerfile
      context: .
    ports:
      - "8080:8080"
    environment:
      - DB_USER=root
      - DB_PASS=password
      - DB_NAME=test
    depends_on:
      - mysql

  mysql:
    image: mysql:5.7
    container_name: mysql
    restart: always
    environment:
      - MYSQL_DATABASE=test
      - MYSQL_ROOT_PASSWORD=password
    ports:
      - "3306:3306"